### ISSUE TITLE
patternplate init server configuration does not match that on patternplate-ui

### ISSUE THREAD

**Issue by cdaringe** [patternplate/patternplate#111]
`init` has different transforms than:

https://github.com/sinnerschrader/patternplate-ui/blob/master/configuration/patternplate-server/patterns.js

i'm betting that -ui's is more up to date, given its babel support

**Comment by marionebl** [comment]
The `patternplate init` config is intended to get first time users ready to walk through the getting started guide without friction, while `ui` has transforms fit for the task of that particular project. Perhaps we should clarify the purpose of the init default configuration?

**Comment by marionebl** [comment]
`patternplate init` was removed for `2.0.0`
