### ISSUE TITLE
Update pattern.json schema to new version

### ISSUE THREAD

**Issue by KnisterPeter** [patternplate/patternplate#125]
Currently the flag attribute for the pattern.json schema consists of 'alpha', 'beta', 'rc' and 'stable'.
There should be a status for end of life of a pattern. A good candidate would be 'deprecated'.

http://json.schemastore.org/pattern

---
* [ ] Add `deprecated` to `flag`
* [ ] Remove `patterns` object

**Comment by marionebl** [comment]
Won't maintain pattern schema any more.
