### ISSUE TITLE
patternlist does not show all tags

### ISSUE THREAD

**Issue by KnisterPeter** [patternplate/patternplate#126]
The list of patterns (e.g. some atoms folder) does not display all tags attached to a pattern.

In the case below the tags should be 'reviewed', 'deprecated', 'documentation-needed' and 'demo-needs-update'.

![tags](https://cloud.githubusercontent.com/assets/327445/20348260/d909b682-ac04-11e6-8285-8347d2e1d1f0.png)

**Comment by marionebl** [comment]
The folder view has been removed for `2.0.0`
