### ISSUE TITLE
Faulty rendering of opacity indicator background on FF

### ISSUE THREAD

**Issue by marionebl** [patternplate/patternplate#131]
Browser: Firefox
OS: Windows

![screenshot](https://cloud.githubusercontent.com/assets/4248851/20763662/4cac6d60-b72b-11e6-84c6-15b5bd75e2bf.png)

**Comment by M-ZubairAhmed** [comment]
can i take this one?

**Comment by marionebl** [comment]
The opacity indicator has been changed for `2.0.0` and works correctly on FF now.
