### ISSUE TITLE
Document ui configuration

### ISSUE THREAD

**Issue by marionebl** [patternplate/patternplate#143]
The ui configuration is rather sophisticated and bound to get more complex via e.g.: https://github.com/sinnerschrader/patternplate/issues/141. 

As a component library IDE intended to also be used by customers and non-techs patternplate has to allow easy control over the actual appearance of the chrome. We should document available options and their limitations to make it easier for

1. Developers seeking to change the current interface appearance
2. Interested parties evaluating the project for usage

**Comment by SaraVieira** [comment]
If you let me know what is possible in the ui.js I can do this documentation 😄

**Comment by marionebl** [comment]
**Defaults**: [source/configuration/ui.js](https://github.com/sinnerschrader/patternplate-client/blob/3b74ff6c7ae800ed48f78c16d49a08588d383cd3/source/configuration/ui.js)

```js
const ui = {
	hierarchy: {
		'sub/path': { // key has to match folder in patterns, e.g. sub/path
			displayName: 'Atoms', // used in ui
			order: 1, // descending order index, lower places item higher in sidebar
			icon: 'atoms' // `id of icon in icons.svg to use. See /static/images/patternplate-icons.svg for available ids`
		}
	},
	resultOrder: [ // most likely out of effect, needs investigation
		'Dependencies',
		'Markup',
		'Script',
		'Style',
		'Documentation'
	],
	theme: 'light', // default theme to use, available: dark, light
	themeTarget: 'dark', // out of effect
	useFolderTable: true // out of effect
};

export default ui;
```

**Comment by SaraVieira** [comment]
So it's that and the other two you told me in issue ?

**Comment by marionebl** [comment]
@SaraVieira I'll have a look into this tomorrow - thanks for your patience!

**Comment by SaraVieira** [comment]
@marionebl No problem :)

**Comment by marionebl** [comment]
Obsolete via 2.0.0
