### ISSUE TITLE
Proposal: Transit map style dependency tree

### ISSUE THREAD

**Issue by Dangoo** [patternplate/patternplate#145]
@marionebl had the idea to give the dependency tree view an update and move the style more towards urban transit maps.

So I researched some famous transit maps and found a very elegant timeless design and its [specification from the London underground](https://tfl.gov.uk/cdn/static/cms/documents/tfl-line-diagram-standard.pdf).

The process requires some concept work on how dependencies become linked and wich scope will be visible to the user initially per pattern.

Here is a first sketch inspired by the london transport map:
![pattern-tree-transit01](https://cloud.githubusercontent.com/assets/1252204/24475506/5c5d1f86-14d0-11e7-9ee5-94e777fef68a.png)

Legend:
- Large headlines ('Station names') are links to the dependencies of each pattern
- The inverted one is the current pattern (e.g. on a pattern detail page)
- The lines show the flow of dependencies relative to the current pattern
- The grey framed names below some stations are links to other patterns including the stations pattern ('Login Form' uses 'Labeled Input')

What do you think? Please add a comment below and vote/downvote this post :)

**Comment by marionebl** [comment]
Taking this down – the dependency tree is low-priority compared to expanding editing (e.g. markdown editor) and integration features (e.g. sketch export).
