### ISSUE TITLE
Documentation navigation

### ISSUE THREAD

**Issue by markusoelhafen** [patternplate/patternplate#150]
Implement a link to the next/previous markdown file at the bottom of the page.
If possible with the title of the next file displayed.

Example image:
<img width="870" alt="screen shot 2017-07-27 at 19 54 56" src="https://user-images.githubusercontent.com/10544994/28684831-16fb7566-7306-11e7-8cc7-253712ce35d3.png">

The next/previous Links should step through the order of the markdown files in a given folder.
The first file in a folder only shows the "next-link", the last file only the "previous-link"

**Comment by marionebl** [comment]
Sounds like a good idea - we also could do the arrow-thing like GitBook:
 
<img width="1133" alt="screen shot 2018-03-09 at 07 07 11" src="https://user-images.githubusercontent.com/4248851/37193069-b9b48546-2368-11e8-8e5e-d71ec60e898d.png">

**Comment by marionebl** [comment]
I came up with a solution sketch for this:

1. **Create selectors for "next" and "previous" doc items**

   ```js
   const selectNext = createSelector(
     selectPool,
     state => state.id,
     (pool, id) => {
        const index = pool.findIndex(i => i.id === id);
        if (index === -1) {
           return null;
        }
        return pool[index + 1];
     }
   );

   const selectPrev = createSelector(
     selectPool,
     state => state.id,
     (pool, id) => {
        const index = pool.findIndex(i => i.id === id);
        if (index === -1) {
           return null;
        }
        return pool[index - 1];
     }
   );
   ```
    
   Changes go here: [packages/client/src/app/containers/documentation.js#L120](https://github.com/patternplate/patternplate/blob/master/packages/client/src/app/containers/documentation.js#L120)

2. **Provide "next" and "previous" doc items to `<Documentation/>` container:**

   ```js
   return {
     // other fields emitted
     next: selectNext(state),
     prev: selecetPrev(state),
   }
   ```
   Changes go to [packages/client/src/app/containers/documentation.js#L123](https://github.com/patternplate/patternplate/blob/master/packages/client/src/app/containers/documentation.js#L123)

4. **Use next and previous props to decide wether to render a link on `<Documentation/>`:**

    ```js
    render () {
      const {props} = this;
      return (
        <StyledDocumentation ref={ref => this.ref = ref}>
          <div id="doctop"/>
            <Helmet title={props.displayName}/>
            {// This is new}
            {props.prev && (
                <DocNavigation symbol="arrow-left" target={props.prev}/>
             )}
            <Markdown
               linkable
               source={props.doc}
               widgets={props.widgets}
               />
            {// This is new}
            {props.next && (
                <DocNavigation symbol="arrow-left" target={props.next}/>
             )}
        </StyledDocumentation>
       );
     }
     ```
     ```js
     import { styled, Link, Icon } from "@patternplate/components";


     function DocNavigation(props) {
       return (
          <Link href={`./docs/${props.id}`} title={`Navigate to ${props.manifest.displayName}`}>
            <Icon symbol={props.symbol} size="L"/>
          </Link>
       );
     }
     ```

Want to lend a hand @markusoelhafen?

**Comment by marionebl** [comment]
Won’t implement this mid term, will reopen if we do.
