### ISSUE TITLE
how to use widgets

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#166]
I read the following guide: https://patternplate.github.io/doc/docs/reference/widgets?guides-enabled=true&patterns-enabled=true&reference-enabled=true

I am still not sure how to use this without taking a look at the source code. 

I think this could be documented better. Maybe it is possible to add a link (look at the source for this page) 

What I'm missing:

* code examples have no filenames (hard to reference)
* The demo shows buttons but there is no link/hint why these are shown. (naming conflict "code, button" ?)
* a link to the source code of that exact example (probably the most important part)
* The main information is IMHO missing. (it explains what widgets are (in an abstract) but the rest remains a mystery 

All in all, it remains a mystery to me.

Screenshot for reference:

<img width="919" alt="screen shot 2018-03-13 at 11 23 14" src="https://user-images.githubusercontent.com/1148334/37336203-f922afd2-26b0-11e8-8cd9-8fdb185e0537.png">

**Comment by pixelass** [comment]
Naming issue `src/code` => `button`



> ## Pattern Demo
> 
> `<PatternDemo />` displays the demo for the pattern referenced via `id`.
> 
> ```js
> const React = require("react");
> const {PatternDemo} = require("@patternplate/widgets");
> 
> module.exports = () => <PatternDemo id="src/code" />;
> ```
> 
> ```widget
> const React = require("react");
> const {PatternDemo} = require("@patternplate/widgets");
> 
> module.exports = () => <PatternDemo id="button" />;
> ```

**Comment by pixelass** [comment]
This should be documented

* id = `pkg.name`
* codeblocks need the ` ```widget ` lang-flag

**Comment by marionebl** [comment]
@pixelass Could you send a PR for the button/code misnomer? Agreed on the docs being a bit lacking.

**Comment by pixelass** [comment]
I can prepare a PR to resolve the naming conflict.
