### ISSUE TITLE
tags have no margin

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#167]
The tags in the markdown files seem to be missing a natural spacing.

<img width="330" alt="screen shot 2018-03-13 at 11 45 43" src="https://user-images.githubusercontent.com/1148334/37337325-31a74afe-26b4-11e8-843c-5db4c6bfabda.png">

**Comment by marionebl** [comment]
Yup, they should have the same spacing between each other as between the tag list and the delimiter border.

I think we could wrap `SearchTrigger` with a `styled-component` here, resulting in a `StyledSearchTrigger` with a `margin-left`.

 Want to lend a hand?

https://github.com/patternplate/patternplate/blob/master/packages/client/src/app/components/pattern/pattern-sheet.js#L45-L47

**Comment by pixelass** [comment]
sure I can look into it.
