### ISSUE TITLE
edit docs (via ...)  link

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#169]
Documentation often provides an "edit on ..." or "improve this ..." link that opens the source on GitHub or similar.

I would like to see something similar.

### Motivation

Readers are more likely to fix typos or contribute to the docs when they see the link. 

Example via Less.js: http://lesscss.org/usage/

<img width="883" alt="screen shot 2018-03-13 at 14 19 01" src="https://user-images.githubusercontent.com/1148334/37344045-87acc356-26c9-11e8-804a-ffb19b41d61d.png">

**Comment by marionebl** [comment]
Closing, moved to #161
