### ISSUE TITLE
JSX syntax highlighting

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#173]
I am using patternplate for a React.js project.

All code blocks in my markdown files are labeled with ` ```jsx `.

Result: nested elements are not highlighted correctly.

Related issues (via hightlight.js): https://github.com/isagalaev/highlight.js/issues?utf8=%E2%9C%93&q=jsx

<img width="766" alt="screen shot 2018-03-13 at 20 04 09" src="https://user-images.githubusercontent.com/1148334/37364495-ffe2326c-26fa-11e8-8a06-bd7f840bf56d.png">

**Comparison: Codemirror.runMode**

*This might be an option.*

```js
CodeMirror.runMode(value, mode, node)
```

<img width="835" alt="screen shot 2018-03-13 at 20 11 15" src="https://user-images.githubusercontent.com/1148334/37364499-022ea172-26fb-11e8-94aa-7daeda9523ea.png">

**Comment by marionebl** [comment]
Sure, let's fix this. 

Let's have a look at https://github.com/craftzdog/react-codemirror-runmode/blob/master/src/index.js to inform our implementation.

**Comment by marionebl** [comment]
Had a look at this, CodeMirror doesn't play well with Node.js apparently :/

**Comment by pixelass** [comment]
Maybe we can find some ideas here:

https://github.com/JedWatson/react-codemirror/issues/21

https://github.com/TypeCtrl/ngx-codemirror/pull/2

**Comment by marionebl** [comment]
Looked into the referenced issues and code mirror def. does not support SSR - the supplied fixes conditionaly omit problematic requires on the server and disable code mirror. 

I don't think there is a straightforward solution given only highlight.js runs universally and seems to have troubles fixing this.

**Comment by marionebl** [comment]
Looking at https://github.com/wooorm/refractor we just might be able to use Prism highlighting on the server. We should give it a spin.

**Comment by marionebl** [comment]
Release as of 2.5.25
