### ISSUE TITLE
config: custom svg logo stroke

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#175]
I am using a custom logo with a stroke. It seems that the attribute is removed.

* `stroke-width`

I tried using `strokeWidth` without any success

## Config

```js
module.exports = {
  logo: `
  <svg height="48" width="48" viewBox="0 0 24 24">
    <rect width="24" height="24" fill="hsl(212, 44%, 29%)"></rect>
    <polygon fill="hsl(50, 70%, 70%)" points="5,5.07 13,5.07 17,12 13,18.92 5,18.92"></polygon>
    <polygon fill="hsl(50, 10%, 90%)" stroke="hsl(212, 44%, 29%)" stroke-width="1" points="9,6.8 15,6.8 18,12 15,17.19 9,17.19"></polygon>
  </svg>`
};

```

## Input

```html
<svg height="48" width="48" viewBox="0 0 24 24">
    <rect width="24" height="24" fill="hsl(212, 44%, 29%)"></rect>
    <polygon fill="hsl(50, 70%, 70%)" points="5,5.07 13,5.07 17,12 13,18.92 5,18.92"></polygon>
    <polygon fill="hsl(50, 10%, 90%)" stroke="hsl(212, 44%, 29%)" stroke-width="1" points="9,6.8 15,6.8 18,12 15,17.19 9,17.19"></polygon>
  </svg>`
```

## Output

```html
<svg class="svg__tag-kcLjg cmiegA" width="48" height="48" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
  <rect class="svg__tag-kcLjg cmiegA" width="24" height="24" fill="hsl(212, 44%, 29%)"></rect>
  <polygon class="svg__tag-kcLjg cmiegA" points="5,5.07 13,5.07 17,12 13,18.92 5,18.92" fill="hsl(50, 70%, 70%)"></polygon>
  <polygon class="svg__tag-kcLjg cmiegA" points="9,6.8 15,6.8 18,12 15,17.19 9,17.19" fill="hsl(50, 10%, 90%)" stroke="hsl(212, 44%, 29%)"></polygon>
</svg>
```

**screenshot**

<img width="50" alt="screen shot 2018-03-13 at 20 54 15" src="https://user-images.githubusercontent.com/1148334/37366435-b80495c4-2700-11e8-8498-3b65a35e5c1c.png">

**expected**

<img width="54" alt="screen shot 2018-03-13 at 20 53 46" src="https://user-images.githubusercontent.com/1148334/37366437-ba1c584c-2700-11e8-9d4b-cce5883a3e5f.png">

## Version

```
node_modules/.bin/patternplate --version
2.0.0-55
```

**Comment by marionebl** [comment]
Jep, we should allow `stroke-width` here: 

https://github.com/patternplate/patternplate/blob/a3748988d708c5bdfa30299236d48e00ded5ca25/packages/client/src/app/utils/svg.js#L12-L16

Want to send a PR for this?

**Comment by pixelass** [comment]
looks like they need to be mapped though or we can simply camelize all props. 


`my-attribute` is not valid in react `myAttribute` is not valid in `SVG`

The string itself should be a valid SVG element.

**Comment by marionebl** [comment]
Sending all allowed props through camelCase: 👍
