### ISSUE TITLE
Can't resolve 'raw-loader'

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#178]
after clearing node_modules and running yarn install

```
patternplate build --out=docs/api
⠋ Building to "docs/api"ModuleNotFoundError: Module not found: Error: Can't resolve 'raw-loader'
```

## Version

```
"@patternplate/cli": "^2.0.0-57",
```

**Comment by marionebl** [comment]
Börks - regression introduced with https://github.com/patternplate/patternplate/commit/56eb890f0562ffc75f7f5e5ea784d0c0ec1bddd8#diff-a42841efb5924227a1ff6ab1d3cc7cbfR31.

**Comment by marionebl** [comment]
I am on a flaky connection, so publishing is a bit of an adventure
