### ISSUE TITLE
Errors in Demo (timing issue?)

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#181]
When starting patternplate I get this error.

The files are being watched. after I save "any" file all errors disappear.

```
patternplate.web.vendors.js:23601 Uncaught TypeError: Cannot read property '@dekk/autoplay/src/demo.js' of undefined
    at getComponent (patternplate.web.vendors.js:23601)
    at main (patternplate.web.vendors.js:23575)
    at Object.<anonymous> (patternplate.web.vendors.js:23580)
    at __webpack_require__ (patternplate.web.vendors.js:55)
    at webpackJsonpCallback (patternplate.web.vendors.js:26)
    at patternplate.web.demo.js:2
```

## Build script

```js
const execa = require('execa')

execa('yarn', ['babel:packages:watch'], {stdio: 'inherit'}).catch(console.error)
execa('yarn', ['patternplate'], {stdio: 'inherit'}).catch(console.error)

```

## Versions

```
 "@patternplate/cli": "^2.0.0-57"
```

**Comment by pixelass** [comment]
related to #155 (very similar behavior)

## Workaround (not a solution)

I am now building the lib to ensure all files exist before starting patternplate.

**Comment by pixelass** [comment]
Seems to be an issue with my build.

(I was removing and creating the lib folder twice).

Feel free to comment below if you experience a similar issue.

**Comment by pixelass** [comment]
Issue still occurs

**Comment by marionebl** [comment]
Can't reproduce / not actionable to me. This most likely is caused by deleting an entire folder watched by patternplate.
