### ISSUE TITLE
URLs cause 404 (gh-pages) static build

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#185]
Steps to reproduce:

1. https://sinnerschrader.github.io/dekk/manual/?references-enabled=true
2. click a link in the sidebar
3. reload page

or 

1. open https://sinnerschrader.github.io/dekk/manual/doc/.manual/reference/installation?references-enabled=true

everything exists in this folder: https://github.com/sinnerschrader/dekk/tree/master/docs/manual/doc/.manual

I checked and found matching index.html files. 

The only issue I could imagine is that the dot `.` in `.manual` could cause a conflict.

### Versions

```
"@patternplate/cli": "^2.0.0-63"
```

**Comment by marionebl** [comment]
Have you tried using `manual` instead of `.manual`? Does that change anything? I think this is not related to patternplate, but gh-pages: 

https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Comment by pixelass** [comment]
I was wondering about it too. I don't see why it wouldn't work. 

I'll create a simple repo with `.foo` in the path and see if that is ignored.

I could imagine that gh-pages treats it as a "hidden folder"

**Comment by pixelass** [comment]
Confirmed:

https://pixelass.github.io/foo/.foo/

https://github.com/pixelass/foo/tree/master/docs/.foo

Can patternplate rename these folders? 

It is obviously an issue if there are 2 folders `.foo` and `foo` and the `.` is simply stripped.

Maybe the names can be hashed instead? `/.foo/bar/baz/.qux/` => `/abc123/bar/baz/xyz789/`

**Comment by pixelass** [comment]
Sidenote: `.manual` is the source docs folder. 

```
{
docs: [".manual/**/*.md"]
}
```

**Comment by marionebl** [comment]
Currently I‘d tend not to implement some magic renamer thing. This might go away on its own when I switch to id instead of path based urls for docs, too

**Comment by marionebl** [comment]
Easy fix would be a .noyekyll file in docs/

**Comment by pixelass** [comment]
I renamed the folder. 

This is such a minor issue for me. At least now it's here for everyone to read.

closing.
