### ISSUE TITLE
Embedding videos

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#187]
Allow including videos in guides.

## Motivation

When using Patternplate to create guides for users I want to be able to include an inline video tutorial.

Markdown allows the following:

```markdown
<a href="http://www.youtube.com/watch?feature=player_embedded&v=w3jLJU7DT5E
" target="_blank"><img src="http://img.youtube.com/vi/w3jLJU7DT5E/0.jpg" 
alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

or

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/w3jLJU7DT5E/0.jpg)](https://www.youtube.com/watch?v=w3jLJU7DT5E)
```
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/w3jLJU7DT5E/0.jpg)](https://www.youtube.com/watch?v=w3jLJU7DT5E)

Maybe this could be a `widget`.

    ```widget
    const React = require("react");
    const {Embed} = require("@patternplate/widgets");

    module.exports = () =>  <Embed service="youtube" id="w3jLJU7DT5E" />;
    ```

    ```widget
    const React = require("react");
    const {YouTube} = require("@patternplate/widgets");

    module.exports = () =>  <YouTube videoId="w3jLJU7DT5E" />;
    ```

**Comment by marionebl** [comment]
I like the idea to implement this via widgets because I don't want to extend markdown with new sytanx. 

Another approach could be to detect markdown images that point to embed urls of video platforms (youtube, vimeo for starters) and do the embed dance the platform requires. What do you think?

**Comment by marionebl** [comment]
Won’t implement this mid term, will reopen if we do.
