### ISSUE TITLE
allow a custom favicon

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#194]
It would be nice to be able to set a favicon (or icons in general)

https://github.com/jantimon/favicons-webpack-plugin

```json
{
    "@patternplate/cli": "2.0.0-87",
}
```

**Comment by marionebl** [comment]
That’s already possible, but undocumented / unstable. Catch me irl and we can talk this through.

I plan to expose / document an ui config with one of the feature releases after 2.0. Favicons would be part of this.

**Comment by marionebl** [comment]
As of 2.3 this is documented, the option is called `ui.favicon`:

https://patternplate.github.io/doc/docs/reference/configuration?guides-enabled=true&reference-enabled=true#ui.favicon
