### ISSUE TITLE
Add Plugins

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#195]
I would love to see plugins to modify PP.

I am mostly looking for a way to add filters or change the viewport size but there
are several other reasons to support this.

Use cases:

* viewport switcher (responsive/testing)
* color changer (a11y/testing)

It would be nice to be able to add them similar to links or patterns

```markdown
---
displayName: A11y
icon: a11y
options:
  order: 100
  plugin: filters
---
```

```markdown
---
displayName: Responsive
icon: a11y
options:
  order: 100
  plugin: viewport
---
```

**Comment by marionebl** [comment]
Sure this will happen at some point in the future, I want to get this right though. 

The plugin API will be modelled after vscode plugins (cc @mabels).

**Comment by marionebl** [comment]
Closing for now as this is not on the roadmap for the immediate future. We'll pop this open again when it comes up.
