### ISSUE TITLE
trying to document a polymer web component

### ISSUE THREAD

**Issue by sebs** [patternplate/patternplate#214]
Hi

I was trying to change the hello-world demo to serve me a polymer component and I got some CORS errors due to the fact that the demo is shown in an iframe. 

What did I do: 

0. Initialized Demo 
1. Installed my  polymer web components under static/bower_components/<mycomponent>
2. changing the demo to the following code. In order to get all my components loaded. 
Result: A CORS error for localhost appears. Looks like these components violate some iframe security .....

Error: 
Access to Imported resource at 'http://localhost:1337/api/static/bower_components/<omponent-name>/bundle-app-shell.html' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

```js
// lib/hello-world/demo.js
module.exports = {
  html: () => `
    <link rel="import" href="/api/static/bower_components/<component-name>/bundle-app-shell.html">
    <h1 class="hello-world" data-hello-world>Hello World</h1>`,
  css: () => '.hello-world { font-family: sans-serif; color: cornflowerblue; cursor: pointer; }',
  default: function() {
    var el = document.querySelector("[data-hello-world]");
    var count = 0;
    el.addEventListener("click", function(e) {
      e.target.textContent = "Hello World, " + (++count);
    });
  }
};
```

Question: can I set lax cors headers for the development setup?

**Comment by marionebl** [comment]
Thanks for reporting!

This might be related to the introduction of a `referrerpolicy="no-referrer"` on iFrames in https://github.com/patternplate/patternplate/commit/890d4e63a71593449951d52c56e12d9d12903902#diff-275dba57d57f2c8ac3cf2530e80384deR17. 

Two things would help a lot with fixing this:

1. Could you confirm the demo works in fullscreen mode? (Reach it by clicking the four arrow icon on the lower right hand side of the pattern demo)

2. Could you provide a minimal reproduction of the issue in a publicly available repo?

**Comment by sebs** [comment]
I have my free day, i will cook something like a example up. 

I have deleted the repos I had after the bug report (very smart, I know) but other tool where "webcomponents" work, do have some of the new iframe properties set. I am not sure though, if that comes with a security flaw by design when this is activated.

**Comment by marionebl** [comment]
I can reproduce this via https://github.com/marionebl/patternplate-cors-issue-repro, at least locally, as in:

1. The iFrame throws an CORS exception
2. The corresponding fullscreen view does not

The static build I pushed does not show this behaviour, presumably because GitHub delivers html files with `Access-Control-Allow-Origin: *`

https://marionebl.github.io/patternplate-cors-issue-repro/pattern/hello-world/?components-enabled=true

**Comment by marionebl** [comment]
Fixed via 2.5.1. Please reopen if your tests create different results

**Comment by sebs** [comment]
ok, will do

**Comment by sebs** [comment]
works now. Thanks
