### ISSUE TITLE
Error warning doesn't close on (x)

### ISSUE THREAD

**Issue by fahrradflucht** [patternplate/patternplate#217]
When getting an error notification it doesn't close when clicking on `x`. It just adds the `js-warning=false` query parameter to the url. The notifications vanishes only after reloading the page.

**Comment by marionebl** [comment]
Ok that is an edge case where `react-router` manages to get its event handlers in place before the crash occurs. 

We need additional state handling at https://github.com/patternplate/patternplate/blob/master/packages/client/src/app/containers/application.js#L160-L163 to make sure the warnings is only visible when `query["js-warning"] !== "false"`.

**Comment by marionebl** [comment]
Fixed via `2.4.1`
