### ISSUE TITLE
No link to medium article from cover page

### ISSUE THREAD

**Issue by MartinHelmut** [patternplate/patternplate#218]
Hey,

if I try to click the "Read the story on Medium" button on the https://patternplate.github.io/ cover there is no link to go to. Related line is: https://github.com/patternplate/patternplate/blob/3c74a9f95dcce9d8631a37eee214beb318fa6ef3/packages/components/src/cover/index.js#L202

If I had found the article on medium, I would have created a PR 😅

**Comment by marionebl** [comment]
Good catch! The article does not exist yet, so there is nothing link. I'll keep this around to remind ourselves.

**Comment by marionebl** [comment]
Fixed via fed983ba89e321ab9e6d483d7e66d14d4b512f5a
