### ISSUE TITLE
'we messed up' error

### ISSUE THREAD

**Issue by chrisanderss0n** [patternplate/patternplate#225]
I see a yellow error message appear at the top of the UI every time I visit my own project as well as the [patternplate hosted on github pages](https://patternplate.github.io).

<img width="791" alt="screen shot 2018-04-27 at 3 52 36 pm" src="https://user-images.githubusercontent.com/6155115/39382384-45fc08a8-4a33-11e8-9cc3-4e4ad21439ca.png">

**Comment by marionebl** [comment]
Hey, could you provide some more details? 

1. Which browser + version are you using to access patternplate?
2. Can you see an exception in the developer console of that browser?

**Comment by chrisanderss0n** [comment]
Ack! Sorry was multitasking:

Chrome Version 65.0.3325.181 on Mac 10.13.4

In dev console I see:  Unexpected token s in JSON at position 0

Appears to be happening on line 30  in patternplate/packages/client/src/app/actions/listen.js

**Comment by marionebl** [comment]
Ok, here is what is happening: `patternplate` registers a global event listener for `"message"` to handle some `postMessage` communication. 

There are some chrome extensions that emit message events that contain `data` that is no valid JSON, which causes line 30 to fail. Fix incoming, thanks for reporting!

**Comment by marionebl** [comment]
Fixed via 2.5.4. Thanks again for reporting.
