### ISSUE TITLE
bug: iframe has a max width of 1240px

### ISSUE THREAD

**Issue by chrisanderss0n** [patternplate/patternplate#227]
The iframe that contains the component code appears to have a maximum width of 1240px. I poked around but could not find where this limitation is set.

If you can point me in the right direction I'll make the change and push it up.

**Comment by marionebl** [comment]
Hey there, the limit is set at https://github.com/patternplate/patternplate/blob/0dd3760354892db02bdc0b674476a2195ba53176/packages/client/src/app/components/pattern/index.js#L68, happy to receive a PR for this! 👍

**Comment by chrisanderss0n** [comment]
https://github.com/patternplate/patternplate/pull/228
