### ISSUE TITLE
IE11 compability issue causes 'Syntax error'

### ISSUE THREAD

**Issue by chunksnbits** [patternplate/patternplate#232]
The angular demo case fails to execute Javascript on the client side, due to some missing ES6 -> ES5 conversions within patternplate client:

Observed: 

On IE11 client side evaluation of the component is being stopped before the initial demo-dependency has been resolved (i.e., the application crashes on a webpack.require statement). The console shows 3 errors: 

![image](https://user-images.githubusercontent.com/1517125/40917280-ed771c84-6802-11e8-9b50-492c25fb0d0d.png)

Expected: 

The client side component is loaded on IE11.

**Comment by marionebl** [comment]
Fix released via @patternplate/client@2.5.13. Thanks again!
