### ISSUE TITLE
Render functions throwing error with version 2.5.19

### ISSUE THREAD

**Issue by LKuechler** [patternplate/patternplate#235]
The change with having the render function be called with await in this PR(https://github.com/patternplate/patternplate/pull/234) seems to cause all none async renderers to throw this error:
`TypeError: render(...).then is not a function`

This is happening because the `await` is change to `.then` in the build process.

A workaround for now is to wrap the render functions in a custom renderer that is async.
Example for `render-styled-components`:
```
const renderStyledComponents = require('@patternplate/render-styled-components/render');

module.exports = render;

async function render(input) {
	return renderStyledComponents(input);
}
```

I will not be able to work on a fix for this until next week. If someone else is interested in fixing this and needs some more information just ask :)

Some more details on how to get the workaround to work:
1. Create a file anywhere in your project and past the example from above in there
2. Change the render option in the `patternplate.config` to point at the new file that you created:
`render: './nameOfYourFile.js'`

**Comment by marionebl** [comment]
Fixed via 2.5.20
