### ISSUE TITLE
Nesting Categories Multiple Times

### ISSUE THREAD

**Issue by annstu** [patternplate/patternplate#238]
We have a lot of content in the documentation, which we want to organize better. We want to nest the categories for a better overview.

**Now:**

```
> Category 1
    - Article 1
    - Article 2
    - Article 3
    - Article 4
```

**What we would like to do:**

```
> Category 1
    > Category 1.1
        - Article 1
        - Article 2
    > Category 1.2
        - Article 3
    > Category 1.3
        - Article 4
```

**Comment by marionebl** [comment]
As discussed with @annstu in person: The tagging/saved search logic adopted via `2.0` does not support this case very well. 

I don't see how we might implement this properly without introducing UI to order/rename/create tree entries in the navigation. Closing for now.
