### ISSUE TITLE
Space after link

### ISSUE THREAD

**Issue by annstu** [patternplate/patternplate#242]
Currently patternplate creates a space after links:

<img width="255" alt="bildschirmfoto_2018-07-17_um_16 20 14" src="https://user-images.githubusercontent.com/40796462/43404666-4e859726-9418-11e8-8338-efc06de80aa8.png">

**Comment by annstu** [comment]
**Update:** This only happens in tables.

**Comment by marionebl** [comment]
Sure, let's fix this.

**Comment by marionebl** [comment]
Released via 2.5.23
