### ISSUE TITLE
Proposal: Add a source code button for the component demo

### ISSUE THREAD

**Issue by larstoepner** [patternplate/patternplate#256]
It would be great if there could be a source code button for the component demo like it was the case in patternplate 1.0 :)

**Comment by marionebl** [comment]
Thanks for the suggestion @larstoepner. Would you mind digging through #239 (might be interesting: https://github.com/patternplate/patternplate/issues/239#issuecomment-412304000). I'd close this issue and consolidate discussion / ideas around this feature over at #239. What do you think?

**Comment by larstoepner** [comment]
yep, do it. thanks :)
