### ISSUE TITLE
Infinite Loading on PP2.0 start. Components won't Load

### ISSUE THREAD

**Issue by larstoepner** [patternplate/patternplate#267]
Hi everyone,

I have a really hard time getting pp2.0 to run right now.

At first it was simply not starting at all. After I ran `npm run dev` I just encountered a blank page with an infinite loading animation at my chrome tab. No error indications whatsoever. I removed `node_modules` and `build`, re-installed everything, ran `npm run build` and `npm run dev.`
Still pp2.0 is not working. In my console I only get the normal "pp2.0 started successfully" messages: 

```
Started on http://localhost:1337
08:58:54 - Compilation complete. Watching for file changes.
```

After some time, it finally started. But now the components won't load. I now get the Error (several times):

```
{ Error: write EPIPE
   at _errnoException (util.js:1022:11)
   at WriteWrap.afterWrite [as oncomplete] (net.js:880:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

I've got this Error before. But it seemed that the components still ran correctly even with this Error shown. So I assume the error does not correlate with the components not loading. (?)

I'm currently on node v8.10.0 and npm  6.4.1
I use Mac and the latest Chrome. But also tried it unsuccessfully on Firefox and Safari.

The behavior is really very strange and I'm sorry I can't provide much more input on the problem.

**Comment by marionebl** [comment]
Hey @larstoepner, thanks for reporting. This was a Heisenbug type of issue in the `^2.5` version range. 

Should be fixed as of version 3, at least you should see error messages in the terminal indicating what went wrong.
