### ISSUE TITLE
Links in the search are not changing the URL correctly

### ISSUE THREAD

**Issue by LKuechler** [patternplate/patternplate#289]
With the url changes the links in the search seem to be broken.

### Steps to reproduce:
1. Open https://patternplate.github.io/doc/docs/why
1. Click on search icon
1. Search for `component` and select the first component

### Expected outcome:
The selected component is displayed and the url should look similar to this
`https://patternplate.github.io/pattern/@patternplate/component-icon.html?search=component`

### Outcome:
The component is not found and a error is displayed
`https://patternplate.github.io/doc/docs/pattern/@patternplate/component-code.html?guides-enabled=true&search=component`

**Comment by kotzendekrabbe** [comment]
and so it comes that @LKuechler was a little bit faster than me 😂 
+1

**Comment by LKuechler** [comment]
@kotzendekrabbe This should now be fixed with the `v3.2.2` version :)
