### ISSUE TITLE
ui.icon & ui.favicon not working

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#293]
WHen adding `ui.logo` or `ui.favicon` I cannot see any changes to the UI.

```js
module.exports = {
	ui: {
		logo: `
		<svg width="30" height="30" viewBox="0 0 30 30">
			<rect width="30" height="30" fill="currentColor"/>
		</svg>
		`,
		favicon: `
		<svg height="30" width="30">
			<circle cx="15" cy="15" r="15"/>
		</svg>
 }
```

<img width="303" alt="screen shot 2018-12-07 at 01 50 14" src="https://user-images.githubusercontent.com/1148334/49620737-867b4f80-f9c2-11e8-8b19-57b04bfa62c3.png">

```bash
01:49 $ yarn patternplate --version
yarn run v1.12.3
$ /<...>/patternplate --version
3.2.2
```

**Comment by marionebl** [comment]
Will try to reproduce and come back to you

**Comment by pixelass** [comment]
Thank you 🙏

**Comment by pixelass** [comment]
Hi. thank you for the quick release. I tested it but can still see the original (pp) logo instead of the one from my config.

`@atternplate/cli: 3.2.3`

**Comment by pixelass** [comment]
My bad. It seems to work now. Not sure what the issue was. 

Thank you again
