### ISSUE TITLE
Failed to load probe (prope)

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#299]
I get an error in the console:

```
patternplate.web.probe.js:1 
Failed to load resource: the server responded with a status of 404 ()
```

The file in the static build is called `patternplate.web.prope.js:1`

`probe` `prope`

<img width="446" alt="screen shot 2018-12-08 at 14 34 44" src="https://user-images.githubusercontent.com/1148334/49686582-d5c29c80-faf6-11e8-830d-de5428a40298.png">

<img width="246" alt="screen shot 2018-12-08 at 14 37 30" src="https://user-images.githubusercontent.com/1148334/49686584-d824f680-faf6-11e8-8764-d6c0458dee7e.png">

```
09:16 $ yarn patternplate --version
yarn run v1.12.3
$ /<....>/node_modules/.bin/patternplate --version
3.2.3
```

**Comment by pixelass** [comment]
Aside from the errors I don't know what this does. Everything seems to work fine.

**Comment by marionebl** [comment]
This a a leftover from an earlier version. Will remove together with solving #294
