### ISSUE TITLE
content.head not respected (Cover)

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#300]
This issue happens when using the cover feature of patternplate.

I am trying to inject a meta tag into the head with SSR support.

I added this code: (expecting it to work)

```js
export const head = () => `
	<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover, user-scalable=yes"/>
`;

export const css = () => `
	body {
		background: red;
	}
`;
```

The css is applied but the meta tag does not appear. (while there is a comment for this in he DOM). I'm not sure if this is not implemented yet or a bug.

I looked at the source code for your own cover and followed the example of using react-helmet but this part has no SSR support and therefore causes an ugly repaint/scale on mobile devices (this is where loading usually take longer so it's very noticeable).

I mainly need this for mobile support. Maybe you can set this one as a default since it will be needed in most cases.

`patternplate 3.2.3`

**Comment by marionebl** [comment]
Does that happen for both the `development` version and the static build?

**Comment by pixelass** [comment]
Yes. 

This is the static file: (shortened)

```html
<head>
    <!-- content.head -->
    <style data-styled="hqlxWj ...">
	    /* STYLED COMPONENTS SSR*/
    </style>
    <style>
        /* content.css */
          
        body {
            background: red;
        }
```

**Comment by pixelass** [comment]
This can easily be done with a custom renderer for patternplate.

```js
const head = typeof input.head === "function" ? input.head() : input.head || "";
```

**with styled-components**

```js
function render(input) {
	const inputHead = typeof input.head === "function" ? input.head() : input.head || "";
	const html = typeof input.html === "function"
		? input.html
		: () => {
			const sheet = new styled.ServerStyleSheet();
			const component = React.createElement(input.default);
			const html = ReactDOMServer.renderToString(sheet.collectStyles(component));
			const head = `${sheet.getStyleTags()}${inputHead}`;
			return {html, head};
		};

	const copy = merge({}, input, {html});
	return renderReact(copy)
}
```
