### ISSUE TITLE
Issues resolving HTML and CSS files.

### ISSUE THREAD

**Issue by zacharyrs** [patternplate/patternplate#322]
Hi!

I'm having a little trouble getting patternplate to behave in my repo (https://github.com/zacharyrs/ssg.z).

I process `./src` to `./lib`, such that...
pattern.json:
```json
{
  "name": "header",
  "displayName": "Header",
  "version": "1.0.0",
  "tags": [],
  "data": {}
}
```

demo.js:
```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.css = exports.html = exports.default = void 0;

var html = _interopRequireWildcard(require("./header.html"));

exports.html = html;

var css = _interopRequireWildcard(require("./header.css"));

exports.css = css;

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = Object.defineProperty && Object.getOwnPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : {}; if (desc.get || desc.set) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } } newObj.default = obj; return newObj; } }

var _default = function _default() {
  console.log('hi');
};


exports.default = _default;
```

header.html:
```html
<p>testing</p>
```

header.css:
```css
/*empty*/
```
In the log, I get...
```
resolve 'header.css' in '/Volumes/data/dev/ssg.z/lib/header'
resolve 'header.html' in '/Volumes/data/dev/ssg.z/lib/header'
```

However unfortunately the page never loads the component, with 'waiting for localhost' bottom left.

**Comment by zacharyrs** [comment]
So, turns out this was just me missing something...

While using babel I used `exports` rather than `module.exports`.
Sadly that doesn't seem to work in this use.

**Comment by zacharyrs** [comment]
Thought I'd fixed it, but it appears not so.

Given demo.js as follows:
```js
module.exports = {
  default: () => {},
  html: `<h1 class="hello-world">Hello World</h1>`,
  css: `.hello-world { font-family: sans-serif; color: cornflowerblue; }`,
}
```

I receive no output.

**Comment by marionebl** [comment]
Thanks for reaching out. You'll want to export functions that return string values of your CSS / HTML like this:

```js
export const html = () => require('./header.html')
export const css = () => require('./header.css')

export default () => {
  console.log('hi')
}
```

or this:

```js
module.exports = {
  default: () => console.log('hi'),
  html: () =>  require('./header.html'),
  css: () => require('./header.css')
}
```

**Comment by marionebl** [comment]
I went ahead and create a PR that demonstrates how to use/write patternplate demos.

I'll close this issue for now as demos appear to work as expected in your setup. Feel free to reopen if the problem persists. Please join the [patternplate Gitter org](https://gitter.im/patternplate/Lobby) for more help. Cheers!

**Comment by zacharyrs** [comment]
Hey!

Thanks a lot for the PR and demo, working wonderfully now!

I think I went wrong by reading the reference rather than the guide!
See [here](https://patternplate.github.io/doc/docs/reference/demos.html), where it implies you can simply export a string.

Is that still valid, or is the doc outdated?
