### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by AdrianoCahete** [patternplate/patternplate#332]
Hey @marionebl @kotzendekrabbe @Palmaswell

This project will receive any update or it's really dead?
The last commit was in April and there's a few PR's opened...

I'm asking just to know if I can fork to fix some problems that I'm facing or if you'll fix in the next months.

**Comment by Palmaswell** [comment]
Hi @AdrianoCahete ,

Thanks so much for reaching out.  This project is currently not under development, yet it's not dead :)
Please feel to create a PR out of your fork and assigned the PR to me.

Please let me know if you have any further questions.
