### ISSUE TITLE
Provide basic documentation already

### ISSUE THREAD

**Issue by marionebl** [patternplate/patternplate#78]
Provide proper documentation for patternplate. This should include:
- [x] Quick Start (Installation, Scaffolding, First start)
- [ ] Create basic overview page via gh-pages
  - [ ] Logo
  - [ ] Button
  - [ ] Headline (h1 - h3)
  - [ ] Image
  - [ ] Paragraph
  - [ ] Link
  - [ ] Text-Teaser
  - [ ] Imprint
- [ ] Pattern driven development; pattern.json, dependencies, formats
- [x] Default project scaffolding [patternplate init]
- [x] Creating your first pattern [Readme in Default project scaffold]

---
- [x] Create: In depth pattern create
- [ ] Show: patternplate ui usage / features
- [ ] Deliver: commonjs, bundles, custom

---
- Advanced: custom transforms, environments, ui configuration, build

---
- [x] Provide patternplate init helper

We could take a lot of cues from the fabricator documentation: http://fbrctr.github.io/advanced/customization.html

**Comment by marionebl** [comment]
The three-step init process now really is 👌 - we should cater it in the future, even after the removal of default configuration and trasforms as planned in https://github.com/sinnerschrader/patternplate/issues/79.

**Comment by Dangoo** [comment]
- [x] Add description for static resources #138

**Comment by marionebl** [comment]
Close via `2.0.0`
